param(
  [string]$ApiBase = "http://localhost:4000/api",
  [string]$Role = "PM"
)

$ErrorActionPreference = "Stop"
$headers = @{ "x-role" = $Role }

function Assert-True {
  param(
    [bool]$Condition,
    [string]$Message
  )

  if (-not $Condition) {
    throw $Message
  }
}

$epic = $null
$story = $null
$task = $null
$comment = $null

try {
  $health = Invoke-RestMethod -Method Get -Uri "$ApiBase/health" -Headers $headers
  Assert-True ($health.ok -eq $true) "Health check failed"

  $epic = Invoke-RestMethod -Method Post -Uri "$ApiBase/epics" -Headers $headers -ContentType "application/json" -Body (@{
    title = "Smoke Epic"
    description = "Generated by smoke-api.ps1"
    priority = 5
  } | ConvertTo-Json)

  Assert-True ([string]::IsNullOrWhiteSpace($epic.id) -eq $false) "Epic creation returned no id"

  $story = Invoke-RestMethod -Method Post -Uri "$ApiBase/stories" -Headers $headers -ContentType "application/json" -Body (@{
    epicId = $epic.id
    title = "Smoke Story"
    description = "Generated by smoke-api.ps1"
    acceptanceCriteria = @("Criterion A", "Criterion B")
    points = 2
    businessValue = 7
    effort = 3
    risk = 2
  } | ConvertTo-Json -Depth 4)

  Assert-True ([string]::IsNullOrWhiteSpace($story.id) -eq $false) "Story creation returned no id"

  $task = Invoke-RestMethod -Method Post -Uri "$ApiBase/tasks" -Headers $headers -ContentType "application/json" -Body (@{
    storyId = $story.id
    title = "Smoke Task"
    assignee = "QA"
    role = "DEVELOPER"
    status = "backlog"
  } | ConvertTo-Json)

  Assert-True ([string]::IsNullOrWhiteSpace($task.id) -eq $false) "Task creation returned no id"

  $updatedTask = Invoke-RestMethod -Method Patch -Uri "$ApiBase/tasks/$($task.id)/status" -Headers $headers -ContentType "application/json" -Body (@{
    status = "done"
  } | ConvertTo-Json)

  Assert-True ($updatedTask.status -eq "done") "Task status update failed"

  $comment = Invoke-RestMethod -Method Post -Uri "$ApiBase/comments" -Headers $headers -ContentType "application/json" -Body (@{
    itemType = "story"
    itemId = $story.id
    author = "Smoke Bot"
    content = "Smoke validation comment"
  } | ConvertTo-Json)

  Assert-True ([string]::IsNullOrWhiteSpace($comment.id) -eq $false) "Comment creation returned no id"

  # Delete epic and verify dependent stories/tasks/comments are cascaded.
  Invoke-RestMethod -Method Delete -Uri "$ApiBase/epics/$($epic.id)" -Headers $headers | Out-Null

  $artifacts = Invoke-RestMethod -Method Get -Uri "$ApiBase/artifacts" -Headers $headers
  $orphans = @($artifacts.comments | Where-Object { $_.itemId -in @($epic.id, $story.id, $task.id) })
  Assert-True ($orphans.Count -eq 0) "Found orphan comments after epic cascade delete"

  [pscustomobject]@{
    status = "passed"
    healthOk = $health.ok
    created = [pscustomobject]@{
      epic = $epic.id
      story = $story.id
      task = $task.id
      comment = $comment.id
    }
    orphanCommentsAfterDelete = $orphans.Count
    apiBase = $ApiBase
    role = $Role
  } | ConvertTo-Json -Depth 6
}
catch {
  Write-Error "Smoke test failed: $($_.Exception.Message)"
  exit 1
}
